services:
  controller:
    build:
      context: .
      dockerfile: docker/controller.Dockerfile
      args:
        UV_VERSION: "0.11.28"

    image: agentguard-controller:dev
    container_name: agentguard-controller

    ports:
      - "8000:8000"

    environment:
      AGENTGUARD_ENV: development
      AGENTGUARD_SANDBOX_IMAGE: agentguard-sandbox:dev
      DOCKER_HOST: unix:///var/run/docker.sock
    
    group_add:
      - "0"

    volumes:
      # 宿主机修改源码后，容器立即看到变化。
      - ./src:/app/src
      - ./tests:/app/tests
      - ./policies:/app/policies
      - ./data:/app/data
      - ./workspaces:/app/workspaces

      # Controller 可以调用 Docker daemon。
      - /var/run/docker.sock:/var/run/docker.sock

    init: true